---
- hosts: web
  sudo: true

  roles:
    - { role: ansible-role-node, tags: [ 'node' ] }
    - { role: ansible-role-users, tags: [ 'users' ] }
    - { role: ansible-role-graphicsmagick, tags: [ 'graphicsmagick' ] }