---
# - name: download and unarchive graphicsMagick version 1.3.22..
#   get_url: url={{ gm_download_url }} dest=~/ timeout=30

- name: unzip gm..
  unarchive: src=~/{{ gm_file }} dest=~/ copy=no
  sudo: false

# file download is so slow and doesnt download the complete file, therefore, unziping does not work and no error is thrown..
# cant continue. so I scp'ed the file and unzipped it, compiled it, and seems to work. no need for CC=clang on ubuntu..
# commands later are:
# ./configure
# make
# sudo make install

# - name: configure gm..
#   command: ./configure CC=clang chdir=~/node
#   sudo: false

# - name: make gm..
#   command: make chdir=~/node
#   sudo: false

# - name: install node
#   command: make install chdir=/home/{{ ansible_ssh_user }}/node
#   sudo: true

# - name: set capabilities to run over port 80
#   command: setcap cap_net_bind_service=+ep /usr/local/bin/node
#   sudo: true

# - name: install pm2
#   npm: name=pm2@latest global=yes
#   sudo: true

# - name: install coffee-script package globally..
#   npm: name=coffee-script global=yes